[package]
name = "mosaic-core"
version = "0.1.0"
edition = "2024"

[dependencies]
dirs = "6.0.0"
jiff = { version = "0.2.31", features = ["serde", "tz-system"] }
log = "0.4.33"
rusqlite = { version = "0.40.1", features = ["bundled"] }
rust-embed = "8.11.0"
rust_decimal = { version = "1.42.1", features = ["serde"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
thiserror = "2.0.18"
toml = "1.1.2"

[dev-dependencies]
tempfile = "3.27.0"
